sonar.projectKey=PALS389_IAC-PALS-0002564608
sonar.organization=PALS389

sonar.projectName=Botón del Caos
sonar.projectVersion=1.0

# Le decimos que solo analice la carpeta app (donde está Python)
sonar.sources=app
sonar.language=py